/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;

import static basiclibrary.Library.roll;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    @Test void testRoll() {
        int[] rolls = roll(10);
        assertEquals(10, rolls.length, "Array length is not 10");
        for (int roll : rolls) {
            assertTrue(roll >= 1 && roll <= 6, "Roll value is out of range");
        }
    }
}
