/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.Random;

public class Library {
    public boolean someLibraryMethod() {

        return true;
    }

    public static int[] roll(int n) {
        int[] rolls = new int[n];
        Random rand = new Random();

        for (int i = 0; i < n; i++) {
            rolls[i] = rand.nextInt(6) + 1;
        }

        return rolls;
    }


}
