/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {

        System.out.println(new App().getGreeting());

        Path gatesPath = Path.of("gates.js");
        System.out.println(gatesPath.toAbsolutePath());
        String errorMessages = checkSemicolons(gatesPath);
        System.out.println(errorMessages);

    }
    public static String checkSemicolons(Path gatesPath) {
//        int lineNumber = 0;
//        HashMap<Integer, String> errors = new HashMap<>();
//
//        try (Scanner scanner = new Scanner(gatesPath)) {
//            while (scanner.hasNextLine()) {
//                String line = scanner.nextLine();
//                lineNumber++;
//
//                if (!line.trim().isEmpty() || !line.trim().endsWith("{") || !line.trim().endsWith("}") || !line.contains("if") || !line.contains("else") || !line.trim().endsWith(";")){
//                    errors.put(lineNumber, "Missing semicolon");
//                }
//            }
//        } catch (Exception e){
//            System.out.println("Error reading file: " + e.getMessage());
//        }
//
//        if (!errors.isEmpty()) {
//            for (Map.Entry<Integer, String> entry : errors.entrySet()) {
//                int line = entry.getKey();
//                String message = entry.getValue();
//                System.out.println("Line " + ": " + message);
//            }
//        } else {
//            System.out.println("No missing semicolons found");
//        }
//        return null;
        List<String> errorMessages = new ArrayList<>();
        int lineNumber = 0;
        Path bufferedReaderGates = Paths.get("gates.js");

        try(BufferedReader reader = Files.newBufferedReader(bufferedReaderGates)) {
            String line = null;
            while((line = reader.readLine()) != null) {

                lineNumber++;
                line = line.trim();
                if (line.isEmpty()){
                    continue;
                }
                char lastChar = line.charAt(line.length() - 1);
                if (lastChar == '{' || lastChar == '}') {
                    continue;
                }
                if (line.contains("if") || line.contains("else")) {
                    continue;
                }
                if (lastChar != ';') {
                    errorMessages.add(String.format("Line %d: Missing semicolon ", lineNumber));
                }
            }
        } catch (IOException ioe) {
            System.out.println("Error reading file: " + ioe.getMessage());
            ioe.printStackTrace();
        }
        return String.join("\n, errorMessages");
    }
}
